---
- hosts: kai
  vars:
    http_port: 80
    max_clients: 200
  # remote_user: root
  tasks:
    - name: Update repositories cache and install "python-pip" package
      sudo: yes
      apt:
        name: python-pip
        update_cache: yes
    - name: Remove "pip" package
      sudo: yes
      apt:
        name: python-pip
        state: absent
    - name: install pip
      sudo: yes
      apt: 
        name: python-pip
        state: present
  # - name: ensure apache is at the latest version
  #   yum: name=httpd state=latest
  # - name: write the apache config file
  #   template: src=/srv/httpd.j2 dest=/etc/httpd.conf
  #   notify:
  #   - restart apache
  # - name: ensure apache is running (and enable it at boot)
  #   service: name=httpd state=started enabled=yes
  # handlers:
  #   - name: restart apache
  #     service: name=httpd state=restarted
...